#!/usr/bin/env bash
# Bash script to modify hosts file
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i 's/157.240.*/8.8.8.8/' ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new